### ISSUE TITLE
global link .jpg

### ISSUE THREAD

**Issue by Marwanrizik91** [WebAhead5/Haifa5#1]
background-image: url(https://internetupstart.com/wp-content/uploads/contactus-background-300x194.jpg);

in this line you used a link from a website, which my be bad for future because that website might shutdown or remove the photo in their side, and you will have a missing elements in your website.
better have the photo with your local files.

**Comment by jrd656** [comment]
I agree. I think it potentially slows the load of our webpage down too. Should be fixed!

**Comment by amirfahoum** [comment]
issue solved, we removed the url link from contact.css,
