### ISSUE TITLE
global review

### ISSUE THREAD

**Issue by Marwanrizik91** [WebAhead5/Haifa5#10]
overall you've done a good website design, with few flaws here and there which is totally normal :smiley_cat: , 
personally i like the slider idea you have made.

the navigation buttons could be more organized and not jump to the middle of the page and then back to the top, try to navigate by page element order.

one last thing, the github page you have is full of files that are not used, i suggest you should put them in a folder and give it a clear name that this files are not used so it doesn't confuse other devs.

**Comment by jrd656** [comment]
> ...with few flaws here and there...

No one likes you Marwan.

But yeah, totally agree. I need to do a lot of tidying.

**Comment by Marwanrizik91** [comment]
> > ...with few flaws here and there...
> 
> No one likes you Marwan.
> 
> But yeah, totally agree. I need to do a lot of tidying.

no cookies for you James :smiling_imp:

**Comment by MoradAbed** [comment]
Thank's Marwan. 
We've re-arranged the navbar titles and the code files.
