### ISSUE TITLE
menu bar visibility 

### ISSUE THREAD

**Issue by JungleSoftTech** [WebAhead5/Haifa5#11]
the navigation bar "about contact team" design and visibility are an clear at some points (when scrolling down)

**Comment by jrd656** [comment]
How do you mean? You can take a screenshot and paste it into your comment

**Comment by majdk143** [comment]
> How do you mean? You can take a screenshot and paste it into your comment

When you scroll down, because the navigation bar has a blur to it, it blurs some text when you scroll down

**Comment by MoradAbed** [comment]
Since it's styling issue and not a code bug/issue we decided to keep the blue effect on the whole bar.
Thank you Khalid!
