### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by hashem96** [WebAhead5/Haifa5#2]
In this line of code : <textarea>Some text...</textarea> 

"Some text" is shown on the frame of the text area as text from the user so the user had to delete the text in order to send his message instead we can write the code as following:

<textarea placeholder="Some text..">

</textarea>

so that the text will disappear automatically after the user click on the text area.

**Comment by jrd656** [comment]
Good idea! @amirfahoum , what do you think?

**Comment by amirfahoum** [comment]
I agree with Hashem , we should use "placeholder".

**Comment by amirfahoum** [comment]
text area Placeholder added.
