### ISSUE TITLE
extra line

### ISSUE THREAD

**Issue by Marwanrizik91** [WebAhead5/Haifa5#3]
https://github.com/WebAhead5/Haifa5/blob/6b87aae051a2b8e96e049c6b7817d30b9a87c252/html/About.html#L9

i think this is an extra line that is not being used. seems more like a comment rather than <h2>

**Comment by jrd656** [comment]
Can you paste the link to the section? It will save us time :-)

Also, these are old .html files that are not linked to the webpage. We should delete them. Good spot!

**Comment by amirfahoum** [comment]
we have deleted About.html file because it was redundant.
