### ISSUE TITLE
Contact form missing attributes

### ISSUE THREAD

**Issue by hashem96** [WebAhead5/Haifa5#8]
You have a lot of css files for styling the website.However, on the side there is nothing related to the section of the contacts us form.Also, the text boxes are too small for the user to write his details.Another thing the submit button is not connected to an email sending action.

**Comment by jrd656** [comment]
@amirfahoum, are you going to take this guy trash talking your contact form??

**Comment by MoradAbed** [comment]
Got it fixed, Thanks, Hashem.
