### ISSUE TITLE
too many css files for one single html file

### ISSUE THREAD

**Issue by JungleSoftTech** [WebAhead5/Haifa5#9]
its always a good idea to have multi css files so we may reuse them in other projects. but in this case the css files are broken down more than necessary which makes it harder for debugging.

**Comment by jrd656** [comment]
Yeah, we could have probably streamlined the file system a bit. We made the decision to split the files up so we could modularise our work and ensure we didn't overwrite each other's work.

**Comment by MoradAbed** [comment]
Thank's Khalid. 
Continuous to what James said before, we split the CSS files in order to fasten the process of building the website - but yeah, we had few extra files that weren't in use.
Re-arranged the files and deleted the unused ones.
